AWSTemplateFormatVersion: 2010-09-09

Transform: AWS::Serverless-2016-10-31

Parameters:
  stage:
    Type: String
  bucket:
    Type: String
  createbucket:
    Type: String

Conditions:
  CreateB:
    Fn::Equals: [!Ref createbucket, true]

Resources:
  Api:
    Type: AWS::Serverless::Api
    Properties:
      DefinitionUri: ./deploy/api.yaml
      StageName: prod
      Variables:
        LambdaFunctionName: !Ref ResizeFunction

  ImageBucket:
    Condition: CreateB
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      AccessControl: PublicRead
      BucketName: !Ref bucket
      WebsiteConfiguration:
        IndexDocument: index.html
        RoutingRules:
          - RedirectRule:
              HttpRedirectCode: 307
              HostName: !Sub ${Api}.execute-api.${AWS::Region}.amazonaws.com
              Protocol: https
              ReplaceKeyPrefixWith: !Sub ${stage}?key=
            RoutingRuleCondition:
              HttpErrorCodeReturnedEquals: 404

  ResizeFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./dist/function.zip
      Handler: index.handler
      Runtime: nodejs6.10
      MemorySize: 1536
      Timeout: 60
      Environment:
        Variables:
          BUCKET: !Ref bucket
          URL: !Sub http://${bucket}.s3-website-us-east-1.amazonaws.com
      Policies:
          Statement:
            - Resource: !Sub arn:aws:s3:::${bucket}
              Effect: Allow
              Action:
                - s3:PutObject

  ResizeFunctionPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref ResizeFunction
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${Api}/*

  ImageBucketPolicy:
    Condition: CreateB
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref ImageBucket
      PolicyDocument:
        Statement:
          - Action: s3:GetObject
            Effect: Allow
            Principal: "*"
            Resource: !Sub arn:aws:s3:::${ImageBucket}/*

Outputs:
  BucketWebsiteUrl:
    Value: !GetAtt ImageBucket.WebsiteURL
  Bucket:
    Value: !Ref ImageBucket
